# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-e011772c-7675-4059-bc05-4738152f9db6".device = "/dev/disk/by-uuid/e011772c-7675-4059-bc05-4738152f9db6";
  boot.initrd.luks.devices."luks-3b6e924c-df1f-434d-ab50-735e91bba361".device = "/dev/disk/by-uuid/3b6e924c-df1f-434d-ab50-735e91bba361";

  boot.resumeDevice = "/dev/mapper/luks-3b6e924c-df1f-434d-ab50-735e91bba361";
    
  fileSystems."/" =
    { device = "/dev/mapper/luks-e011772c-7675-4059-bc05-4738152f9db6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FE07-A91E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3b6e924c-df1f-434d-ab50-735e91bba361"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
