# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-061250de-4f0b-4523-9771-b963bb27f3d2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-061250de-4f0b-4523-9771-b963bb27f3d2".device = "/dev/disk/by-uuid/061250de-4f0b-4523-9771-b963bb27f3d2";
  boot.initrd.luks.devices."luks-ccabdde5-d2c5-4f38-8b08-56e3098301da".device = "/dev/disk/by-uuid/ccabdde5-d2c5-4f38-8b08-56e3098301da";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4140-8248";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ccabdde5-d2c5-4f38-8b08-56e3098301da"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
