{
  config,
  lib,
  ...
}:
let
  cfg = config.agent;
  defaultCfg = config.defaultConfigs.agents;

  agentsDocument = ''
    <!-- Generated by nixenv. Do not edit directly. -->
    <!-- Edit assets/AGENTS.md or defaultConfigs.agents.extraFiles/extraSections instead. -->

  ''
  + builtins.readFile defaultCfg.globalFile
  + lib.optionalString (defaultCfg.extraFiles != [ ]) (
    "\n\n" + lib.concatMapStringsSep "\n\n" builtins.readFile defaultCfg.extraFiles
  )
  + lib.optionalString (defaultCfg.extraSections != [ ]) (
    "\n\n" + lib.concatStringsSep "\n\n" defaultCfg.extraSections
  );
in
with lib;
{
  options = {
    agent = {
      skills = mkOption {
        type = types.listOf types.path;
        default = [ ];
        description = "List of skill directories (each containing a SKILL.md) to symlink into ~/.agents/skills/";
      };
    };

    defaultConfigs.agents = {
      enable = mkEnableOption "generate ~/AGENTS.md from shared and machine-specific fragments";

      globalFile = mkOption {
        type = types.path;
        default = ../../../assets/AGENTS.md;
        description = "Shared AGENTS.md fragment used as the base for generated ~/AGENTS.md.";
      };

      extraFiles = mkOption {
        type = types.listOf types.path;
        default = [ ];
        description = "Additional AGENTS.md fragments appended after the shared global file.";
      };

      extraSections = mkOption {
        type = types.listOf types.lines;
        default = [ ];
        description = "Additional Markdown fragments appended after globalFile and extraFiles.";
      };
    };
  };

  config = mkMerge [
    (mkIf (cfg.skills != [ ]) {
      home.file = builtins.listToAttrs (
        builtins.map (skillPath: {
          name = ".agents/skills/${builtins.unsafeDiscardStringContext (builtins.baseNameOf skillPath)}";
          value.source = skillPath;
        }) cfg.skills
      );
    })

    (mkIf defaultCfg.enable {
      home.file."AGENTS.md".text = agentsDocument;
    })
  ];
}
