-- This is a user-managed declarative config, not Hyprland's generated starter.
hl.config({ autogenerated = false })

-- Monitors
hl.monitor({
    output = "desc:Dell Inc. DELL U3419W 809V5T2",
    mode = "3440x1440@59.97",
    position = "0x0",
    scale = 1,
})
hl.monitor({
    output = "desc:Visitech AS VITURE Beast",
    mode = "3840x1080@60",
    position = "-200x360",
    scale = 1,
})
hl.monitor({
    output = "desc:BOE NE135A1M-NY1",
    mode = "2880x1920@120",
    position = "1000x1440",
    scale = 2,
})

-- Environment
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Prefer native Wayland backends over XWayland.
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("GDK_BACKEND", "wayland")

-- Settings
hl.config({
    general = {
        gaps_in = 2,
        gaps_out = { top = 4, right = 2, bottom = 4, left = 2 },

        border_size = 2,

        col = {
            active_border = {
                colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
                angle = 45,
            },
            inactive_border = "rgba(595959aa)",
        },

        resize_on_border = false,
        allow_tearing = false,
        layout = "master",
    },

    decoration = {
        rounding = 4,
        rounding_power = 3,

        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
            color = 0xee1a1a1a,
        },

        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
        mfact = 0.66,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = false,
    },

    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_rules = "",
        kb_options = "",

        follow_mouse = 1,
        sensitivity = 0,

        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
        },

        natural_scroll = true,
    },
})

-- Animation curves
hl.curve("easeOutQuint", {
    type = "bezier",
    points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { { 0.5, 0.5 }, { 0.75, 1.0 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})

-- Animations
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- Keybindings
local meh = "SUPER + ALT + CTRL"

local function bindWorkspace(key, index)
    hl.bind(meh .. " + " .. key, hl.dsp.focus({ workspace = index }))
    hl.bind(meh .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = index }))
end

local digitKeys = "123456789"
for i = 1, #digitKeys do
    bindWorkspace(digitKeys:sub(i, i), i - 1)
end

local disabledLetterKeys = { Q = true, W = true, F = true }
local letterKeys = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
for i = 1, #letterKeys do
    local key = letterKeys:sub(i, i)
    if not disabledLetterKeys[key] then
        bindWorkspace(key, i + 9)
    end
end

hl.bind(meh .. " + SHIFT + W", hl.dsp.window.close())
hl.bind(meh .. " + SHIFT + Q", hl.dsp.exit())

hl.bind(meh .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(meh .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(meh .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(meh .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(meh .. " + return", hl.dsp.layout("swapwithmaster"))
hl.bind(meh .. " + minus", hl.dsp.layout("mfact -0.01"))
hl.bind(meh .. " + equal", hl.dsp.layout("mfact +0.01"))

hl.bind(meh .. " + SHIFT + slash", hl.dsp.window.float({ action = "toggle" }))
hl.bind(meh .. " + SHIFT + equal", hl.dsp.window.fullscreen())

hl.bind(meh .. " + grave", hl.dsp.workspace.toggle_special("magic"))
hl.bind(meh .. " + SHIFT + grave", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind("SUPER + space", hl.dsp.exec_cmd("@wofi@ --show drun"))

-- With no workspace selector, workspace.move moves the active workspace.
hl.bind(meh .. " + period", hl.dsp.workspace.move({ monitor = "+1" }))
hl.bind(meh .. " + comma", hl.dsp.workspace.move({ monitor = "-1" }))

local lockedRepeating = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"), lockedRepeating)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"), lockedRepeating)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), lockedRepeating)
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), lockedRepeating)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), lockedRepeating)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), lockedRepeating)

local locked = { locked = true }
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), locked)
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), locked)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), locked)
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), locked)

hl.bind(meh .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(meh .. " + SHIFT + mouse:272", hl.dsp.window.resize(), { mouse = true })

-- Window rules
hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})
