// SXWM configuration, generated by nixenv (modules/home-manager/sxwm).
// It follows the niri configuration in ../niri/config.kdl where SXWM has an
// equivalent.
const { wm } = await import("sxwm");

// niri sets these for the processes it starts. SXWM has no environment
// setting, so every spawn exports them first.
const environment =
  "export QT_QPA_PLATFORM=wayland ELECTRON_OZONE_PLATFORM_HINT=wayland GDK_BACKEND=wayland; ";
const spawn = (command) => wm.process.spawn(environment + command);
// meh is Super+Alt+Ctrl, as in the niri configuration.
const meh = "Super+Alt+Ctrl";

await wm.input.configure({
  focus_follows_mouse: true,
  keyboard: { layout: "us", repeat_delay: 225, repeat_rate: 25 },
  pointers: [
    { match: { type: "touchpad" }, natural_scroll: true, disable_while_typing: true },
    { match: { type: "mouse" }, natural_scroll: true },
  ],
});

// SXWM matches outputs by connector name or EDID description, like niri.
// "Unknown" stands for a missing serial.
await wm.outputs.configure({
  outputs: [
    {
      name: "Dell Inc. DELL U3419W 809V5T2",
      mode: { width: 3440, height: 1440, refresh: 59970 },
      position: { x: 0, y: 0 },
      scale: 1,
    },
    {
      name: "Visitech AS VITURE Beast Unknown",
      mode: { width: 1920, height: 1080, refresh: 60000 },
      position: { x: 760, y: 360 },
      scale: 1,
    },
    {
      name: "Samsung Electric Company Display Unknown",
      mode: { width: 3840, height: 2160, refresh: 60000 },
      position: { x: -920, y: 1440 },
      scale: 2,
    },
    {
      name: "BOE NE135A1M-NY1 Unknown",
      mode: { width: 2880, height: 1920, refresh: 120000 },
      position: { x: 1000, y: 1440 },
      scale: 2,
    },
    {
      name: "LG Display 0x07C6 Unknown",
      mode: { width: 2880, height: 1800, refresh: 120000 },
      position: { x: 1000, y: 1440 },
      scale: 2,
    },
  ],
});

// The fixed niri workspaces become the tags.
const tags = ["U", "I", "O", "P", "J", "K", "L"];
await wm.tags.define(tags.map((id) => ({ id, name: id })));
for (const tag of tags) {
  const key = tag.toLowerCase();
  wm.bind(`${meh}+${key}`, () => wm.tags.toggle(tag));
  wm.bind(`${meh}+Shift+${key}`, () => wm.windows.set_tag(tag));
}

wm.bind(`${meh}+w`, () => wm.windows.close());
wm.bind(`${meh}+Shift+q`, () => wm.sxwm.quit());
wm.bind(`${meh}+Left`, () => wm.windows.cycle("previous"));
wm.bind(`${meh}+Right`, () => wm.windows.cycle("next"));

wm.bind("Super+space", () => spawn("@fuzzel@"));
wm.bind(`${meh}+space`, () => spawn("@window-switcher@"));

const locked = { whenLocked: true };
const keys = {
  XF86AudioRaiseVolume: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+",
  XF86AudioLowerVolume: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-",
  XF86AudioMute: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
  XF86AudioMicMute: "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle",
  XF86MonBrightnessUp: "brightnessctl -e4 -n2 set 5%+",
  XF86MonBrightnessDown: "brightnessctl -e4 -n2 set 5%-",
  XF86AudioNext: "playerctl next",
  XF86AudioPause: "playerctl play-pause",
  XF86AudioPlay: "playerctl play-pause",
  XF86AudioPrev: "playerctl previous",
};
for (const [key, command] of Object.entries(keys)) {
  wm.bind(key, () => spawn(command), locked);
}

@extraConfig@
