// SXWM configuration, generated by nixenv (modules/home-manager/sxwm).
// It follows the niri configuration in ../niri/config.kdl where SXWM has an
// equivalent.
const { wm, layouts } = await import("sxwm");

// niri sets these for the processes it starts. SXWM has no environment
// setting, so every spawn exports them first.
const environment =
  "export QT_QPA_PLATFORM=wayland ELECTRON_OZONE_PLATFORM_HINT=wayland GDK_BACKEND=wayland; ";
const spawn = (command) => wm.process.spawn(environment + command);
// meh is Super+Alt+Ctrl, as in the niri configuration, and hyper is
// meh+Shift.
const meh = "Super+Alt+Ctrl";
const hyper = `${meh}+Shift`;

await wm.input.configure({
  focus_follows_mouse: true,
  keyboard: { layout: "us", repeat_delay: 225, repeat_rate: 25 },
  pointers: [
    { match: { type: "touchpad" }, natural_scroll: true, disable_while_typing: true },
    { match: { type: "mouse" }, natural_scroll: true },
  ],
  cursor: { theme: "@cursor-theme@", size: @cursor-size@ },
});

// SXWM matches outputs by connector name or EDID description, like niri.
// "Unknown" stands for a missing serial.
await wm.outputs.configure({
  outputs: [
    {
      name: "Dell Inc. DELL U3419W 809V5T2",
      mode: { width: 3440, height: 1440, refresh: 59970 },
      position: { x: 0, y: 0 },
      scale: 1,
    },
    {
      name: "Visitech AS VITURE Beast Unknown",
      mode: { width: 1920, height: 1080, refresh: 60000 },
      position: { x: 760, y: 360 },
      scale: 1,
    },
    {
      name: "Samsung Electric Company Display Unknown",
      mode: { width: 3840, height: 2160, refresh: 60000 },
      position: { x: -920, y: 1440 },
      scale: 2,
    },
    {
      name: "BOE NE135A1M-NY1 Unknown",
      mode: { width: 2880, height: 1920, refresh: 120000 },
      position: { x: 1000, y: 1440 },
      scale: 2,
    },
    {
      name: "LG Display 0x07C6 Unknown",
      mode: { width: 2880, height: 1800, refresh: 120000 },
      position: { x: 1000, y: 1440 },
      scale: 2,
    },
  ],
});

// The fixed niri workspaces become the tags.
const tags = ["U", "I", "O", "P", "J", "K", "L"];
await wm.tags.define(tags.map((id) => ({ id, name: id })));

// Bindings repeat while held. These options turn that off for actions that
// must not run twice: closing, quitting, starting programs, and toggles.
const once = { repeat: false };
const locked = { whenLocked: true };

const focusedWindow = (state) => state.windows.find((window) => window.focused);

// The screen before (-1) or after (+1) the active screen. Screens go from
// top to bottom by their centers, then from left to right, and the order
// wraps around.
function neighborScreen(state, step) {
  const center = (screen) => [screen.y + screen.height / 2, screen.x + screen.width / 2];
  const screens = [...state.screens].sort((a, b) => {
    const [ay, ax] = center(a);
    const [by, bx] = center(b);
    return ay - by || ax - bx;
  });
  const index = screens.findIndex((screen) => screen.id === state.active_screen);
  if (screens.length < 2 || index === -1) return undefined;
  return screens[(index + step + screens.length) % screens.length];
}

// meh+letter switches to the tag. If a screen shows the tag, focus moves to
// that screen. Otherwise the tag appears on the active screen, and the other
// tags of that screen disappear.
async function switchToTag(tag) {
  const state = await wm.state.get();
  const screen = state.tags.find((candidate) => candidate.id === tag)?.screen ?? null;
  if (screen !== null) {
    await wm.tags.focus(tag);
    return;
  }
  const others = state.screens.find((candidate) => candidate.id === state.active_screen)?.tags ?? [];
  // Send all requests at once, so that SXWM can handle them together.
  await Promise.all([wm.tags.toggle(tag), ...others.map((other) => wm.tags.toggle(other))]);
}

async function focusScreen(step) {
  const state = await wm.state.get();
  const screen = neighborScreen(state, step);
  if (screen) await wm.screens.focus(screen.id);
}

// The focused window gets the newest tag of the neighbor screen, and focus
// follows it. If that screen shows no tag, the first hidden tag appears there.
async function moveWindowToScreen(step) {
  const state = await wm.state.get();
  const window = focusedWindow(state);
  const screen = neighborScreen(state, step);
  if (!window || !screen) return;
  let tag = screen.tags.at(-1);
  if (tag === undefined) {
    tag = state.tags.find((candidate) => candidate.screen === null)?.id;
    if (tag === undefined) return;
    await wm.tags.toggle(tag, screen.id);
  }
  await wm.windows.set_tag(tag, window.id);
  await wm.windows.focus(window.id);
}

// meh+b cycles the layout of the active screen through this list.
await wm.layout("columns", layouts.columns);
const layoutCycle = ["rolodex", "columns"];

const activeScreen = (state) => state.screens.find((screen) => screen.id === state.active_screen);

async function cycleLayout() {
  const screen = activeScreen(await wm.state.get());
  if (!screen) return;
  const index = layoutCycle.indexOf(screen.layout);
  await wm.layouts.set(layoutCycle[(index + 1) % layoutCycle.length], screen.id);
}

// meh+Left and meh+Right move focus to the previous or next window in open
// order. The Rolodex and the columns both order windows this way. Focus stops
// at the first and last window.
async function focusNeighborWindow(step) {
  const state = await wm.state.get();
  const screen = activeScreen(state);
  if (!screen) return;
  // state.windows is in stack order, so the first tiled window is the
  // Rolodex's current window.
  const tiled = state.windows.filter(
    (window) => window.screen === screen.id && !window.floating && !window.fullscreen,
  );
  const current = tiled.find((window) => window.focused) ?? tiled[0];
  if (!current) return;
  const ordered = [...tiled].sort((a, b) => a.id - b.id);
  const target = ordered[ordered.indexOf(current) + step];
  if (target) await wm.windows.focus(target.id);
}

async function withFocusedWindow(action) {
  const window = focusedWindow(await wm.state.get());
  if (window) await action(window);
}

for (const tag of tags) {
  const key = tag.toLowerCase();
  wm.bind(`${meh}+${key}`, () => switchToTag(tag), once);
  // hyper+letter moves the focused window to the tag and does not switch.
  wm.bind(`${hyper}+${key}`, () => wm.windows.set_tag(tag), once);
  // meh+t, then the letter alone, shows or hides the tag on the active screen.
  wm.bind(`${meh}+t ${key}`, () => wm.tags.toggle(tag), once);
}

wm.bind(`${meh}+w`, () => wm.windows.close(), once);
wm.bind(`${hyper}+q`, () => wm.sxwm.quit(), once);
wm.bind(`${meh}+Left`, () => focusNeighborWindow(-1));
wm.bind(`${meh}+Right`, () => focusNeighborWindow(1));
wm.bind(`${meh}+b`, () => cycleLayout(), once);
wm.bind(`${meh}+Up`, () => focusScreen(-1));
wm.bind(`${meh}+Down`, () => focusScreen(1));
wm.bind(`${hyper}+Up`, () => moveWindowToScreen(-1));
wm.bind(`${hyper}+Down`, () => moveWindowToScreen(1));
// The focused window goes to the front of the Rolodex.
wm.bind(`${meh}+Return`, () => withFocusedWindow((window) => wm.windows.focus(window.id)), once);
wm.bind(
  `${hyper}+slash`,
  () => withFocusedWindow((window) => wm.windows.set_floating(!window.floating, window.id)),
  once,
);
wm.bind(
  `${hyper}+equal`,
  () => withFocusedWindow((window) => wm.windows.set_fullscreen(!window.fullscreen, window.id)),
  once,
);

wm.bind("Super+space", () => spawn("@fuzzel@"), once);
wm.bind(`${meh}+space`, () => spawn("@window-switcher@"), once);

// Volume and brightness repeat while held. Media keys run once.
const repeatingKeys = {
  XF86AudioRaiseVolume: "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+",
  XF86AudioLowerVolume: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-",
  XF86MonBrightnessUp: "brightnessctl -e4 -n2 set 5%+",
  XF86MonBrightnessDown: "brightnessctl -e4 -n2 set 5%-",
};
const onceKeys = {
  XF86AudioMute: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
  XF86AudioMicMute: "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle",
  XF86AudioNext: "playerctl next",
  XF86AudioPause: "playerctl play-pause",
  XF86AudioPlay: "playerctl play-pause",
  XF86AudioPrev: "playerctl previous",
};
for (const [key, command] of Object.entries(repeatingKeys)) {
  wm.bind(key, () => spawn(command), locked);
}
for (const [key, command] of Object.entries(onceKeys)) {
  wm.bind(key, () => spawn(command), { ...locked, ...once });
}

@extraConfig@
