# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

let
  optionalDataMountOptions = [
    "nofail"
    "x-systemd.automount"
    "x-systemd.device-timeout=90s"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.swraid.enable = true;
  boot.swraid.mdadmConf = ''
    MAILADDR root
  '';
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "uas"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];

  # The storage stack uses LVM slices, MD RAID, and an outer LVM group.
  # Activate the outer group after MD creates its device.
  boot.initrd.systemd = {
    enable = true;
    services.activate-raid-vg = {
      description = "Activate the outer RAID LVM group";
      wantedBy = [ "initrd.target" ];
      before = [ "initrd.target" ];
      requires = [ "dev-md-surmlinux:0.device" ];
      after = [ "dev-md-surmlinux:0.device" ];
      unitConfig.JobTimeoutSec = "90s";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "/bin/lvm vgchange -ay raid";
      };
    };
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dad4f557-7ba1-4a45-8712-e41f71c692e9";
    fsType = "ext4";
  };

  fileSystems."/dumpdump" = {
    device = "/dev/disk/by-uuid/069483d8-8f1f-412f-90e7-4d86e23d8dbd";
    fsType = "ext4";
    options = optionalDataMountOptions;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D3AC-541C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/dump" = {
    device = "/dev/disk/by-uuid/f2201068-c6cc-4179-be7f-2aa0b0e8c861";
    fsType = "ext4";
    options = optionalDataMountOptions;
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/5732b5f2-cfd6-422d-a124-ff3c66aa9c5b"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
