# surm-auth v2 on Nexus (auth-rework sections 5 and 6).
#
# The container itself, its bind mounts (persistent state parent and
# read-only credential directory), the LoadCredential handoff, and the
# dependency ordering on secrets.service are all generated by the
# surmhosting module from services.surmhosting.auth (see default.nix).
#
# This file only declares where the three existing auth secrets decrypt
# on Nexus. The age files are shared with Pylon, which keeps its copies
# for the rollback window; adding the Nexus recipient requires an
# operator re-encryption (`nix run .#secrets -- recrypt` for these
# three items). No secret values live in this repository.
{
  secrets.items.surm-auth-github-client-id = {
    target = "/var/lib/surm-auth-credentials/github-client-id";
    mode = "0600";
  };
  secrets.items.surm-auth-github-client-secret = {
    target = "/var/lib/surm-auth-credentials/github-client-secret";
    mode = "0600";
  };
  secrets.items.surm-auth-cookie-secret = {
    target = "/var/lib/surm-auth-credentials/cookie-secret";
    mode = "0600";
  };

  # Nexus owns the persistent auth state and credential directories.
  systemd.tmpfiles.rules = [
    "d /var/lib/surm-auth-state 0700 root root -"
    "d /var/lib/surm-auth-credentials 0700 root root -"
  ];

  # Order decryption after tmpfiles setup so the prelude's mkdir -p never
  # races ahead of the directory owner.
  systemd.services.secrets = {
    after = [ "systemd-tmpfiles-setup.service" ];
    requires = [ "systemd-tmpfiles-setup.service" ];
  };
}
